### PR TITLE
Feature/cuda

### PR DESCRIPTION
**Pull request by stevenguh**
This pull request is to support the built-in device conversion like `.to(device)` for the model created by `vggish()`
Previously, one has to set the parameters in the Postprocessor directly to like
```python
model.pproc._pca_matrix = model.pproc._pca_matrix.cuda()
model.pproc._pca_means = model.pproc._pca_means.cuda()
``` 
Additionally, this pull request also allow users to create a VGGish model without its pretrained parameters, which would be helpful for users load a custom state_dict after a transfer learning.

### CODE REVIEW

**Comment by harritaylor** [comment]
Hi @stevenguh, I'm so sorry, I totally missed your PR and I got around to a refactor I've been putting off for a while and the codebase has changed a bit with https://github.com/harritaylor/torchvggish/commit/de6d377fce802f3bc98240306309ff3c8339d925. 
If it isn't too much trouble, please can you adapt your changes with the current state of the repo and I'll merge the PR. Thank you.

(if you don't have time, let me know and I'll deal with it tomorrow at some point)

**Comment by stevenguh** [comment]
That's okay. Thank you for the reply. I am glad you are working the repo. I merged your changes, there is something I couldn't do is that I would love to convert the pca state dict to torch, so no conversion is needed in code as indicated as a TODO in the comment.

Another small suggestion that I think VGGish should compose a VGG instead of inherit from it.

I also changed the `train` param name to `pretrained` to be more aligned with the pytorch's param naming.

**Comment by harritaylor** [comment]
Fantastic, thank you! That makes sense. I was still very new to torch when I wrote this, so I appreciate the changes to make the codebase more canoncial. 

> Another small suggestion that I think VGGish should compose a VGG instead of inherit from it.

I used inheritance in order to abstract away the core model (VGG) from the pre and post processing which makes it VGGish. However I think you're right: I don't think there is any benefit anymore to having VGG as it's own separate model, I just did it this way as it caused less friction for my particular use case.

Thank you very much for contributing, I really appreciate it!

**Comment by stevenguh** [comment]
Thank you for merging my pull request. I appreciate this library as it helps me to do a simple transfer learning with VGGish on pytorch.

**Comment by harritaylor** [comment]
@stevenguh You're welcome - I'm glad it's useful. Thanks for the attention you're giving to make this a more useful library. I would like to add Yamnet to this repo soon, so your help with that would be really appreciated too :)

**Comment by stevenguh** [comment]
It would be cool to have Yamnet. Let me know if you need any help.

**Comment by harritaylor** [comment]
@stevenguh I've just been working through yamnet conversion and have this so far: https://github.com/harritaylor/torchvggish/blob/yamnet/models/yamnet/tf2pt.ipynb

they do some interesting things in the codebase, I was wondering if you had time if you could check my work so far? I'll be updating this rapidly over the next few days, so no worries if you don't have time. Cheers.

**Comment by stevenguh** [comment]
Sorry I am working on other project. I might not have time to look at it, at least this week.

**Comment by harritaylor** [comment]
No problem, do not worry about it. After spending the last few days working on it I believe that it won’t be possible due to the way weights are represented between Keras and pytorch, so I am abandoning the idea for now. If you are interested in the future, please let me know.

-------------------------------------
Harri Taylor
PhD Student
Crime & Security Research Institute
School Of Computer Science &
Informatics
Cardiff University
-------------------------------------
Harri Taylor
Myfyriwr PhD
Sefydliad Ymchwil Trosedd a
Diogelwch
Yr Ysgol Cyfrifiadureg a Gwybodeg
Prifysgol Caerdydd
-------------------------------------
________________________________

**Pull request merged**
